language: csharp

addons:
  apt:
    packages:
      - libimage-exiftool-perl

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: CONFIGURATION=Debug DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: CONFIGURATION=Release DOTNETCORE=1

script:
  - dotnet restore
  - cd src/NExifTool
  - dotnet build -c $CONFIGURATION -f netstandard1.6
  - cd ../../test/NExifTool.Tests
  - dotnet build -c $CONFIGURATION -f netcoreapp1.1
  - dotnet test -c $CONFIGURATION -f netcoreapp1.1
