language: csharp

addons:
  apt:
    packages:
      - libimage-exiftool-perl

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.0.0
      mono: none
      env: CONFIGURATION=Debug DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.0.0
      mono: none
      env: CONFIGURATION=Release DOTNETCORE=1

script:
  - dotnet restore
  - cd src/NExifTool
  - dotnet build -c $CONFIGURATION
  - cd ../../test/NExifTool.Tests
  - dotnet build -c $CONFIGURATION
  - dotnet test -c $CONFIGURATION
